name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal

      - name: Install .NET WASM Build Tools
        run: dotnet workload install wasm-tools

      - name: Publish .NET Core Project
        run: dotnet publish ./MoS.Web/MoS.Web.csproj -c:Release -p:GHPages=true -o dist/Web --nologo

      - name: Commit wwwroot to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.6.5
        with:
          folder: 'dist/Web/wwwroot'
          branch: 'gh-pages'
          single-commit: true
